["protostar.config"]
protostar_version = "0.2.5"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
hole0 = [
    "src/hole0.cairo",
]

["protostar.shared_command_configs"]
stdout-on-success = true