["protostar.config"]
protostar_version = "0.2.5"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
hole0 = [
    "src/hole0.cairo",
]

["protostar.build"]
cairo-path = ["./lib/cairo_math_64x61/contracts"]

["protostar.test"]
cairo-path = ["./lib/cairo_math_64x61/contracts"]